# Generated by Django 4.1.7 on 2023-04-30 07:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='评论正文'),
        ),
    ]
