# Generated by Django 4.1.7 on 2023-04-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='py',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
