# Generated by Django 4.1.7 on 2023-04-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_py'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='py',
            new_name='pv',
        ),
    ]
